# Generated by Django 4.1.1 on 2022-09-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUsers',
            fields=[
                ('user_id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=260)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField()),
                ('is_live', models.CharField(default='1', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
