# Generated by Django 4.1.1 on 2022-09-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_registerusers_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUsers',
            fields=[
                ('user_id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=260)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_live', models.CharField(default='1', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterUsers',
        ),
    ]
