# Generated by Django 4.1.1 on 2022-10-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_contact_alter_registeredusers_is_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredCollege',
            fields=[
                ('user_id', models.CharField(default='b56b722a-f6ea-4e25-9472-b603ff331ce6', max_length=55, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=14)),
                ('state', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('area', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=260)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_live', models.CharField(default='0', max_length=2)),
            ],
        ),
    ]
