# Generated by Django 4.1.1 on 2022-10-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_registeredcollege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredcollege',
            name='user_id',
            field=models.CharField(default='774cfbca-c718-4663-94ef-c5877df995ca', max_length=55, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='user_id',
            field=models.UUIDField(default='5ce1d3ed-29fc-4f69-87ca-0df5728c0acc', primary_key=True, serialize=False),
        ),
    ]
